### ISSUE TITLE
Could the Studio code completion behaviour be reproduced in VScode?

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/vscode-objectscript#1028]
[Related discussion on DC](https://community.intersystems.com/post/intellisense-and-code-completion-vs-code-objectscript)

**Comment by isc-bsaviano** [comment]
This is something that would be done by the Language Server. We've avoided doing type inferencing so far due to the difficulty in determining accurate type information without a parse tree. Studio's behavior could be replicated but it is pretty unreliable and improving on it is not a trivial amount of work.

**Comment by isc-bsaviano** [comment]
Moved to the Language Server repo
