### ISSUE TITLE
Show indicator that a class is only saved, but not compiled

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1033]
In Studio, when a class is only saved, shows a little plus near the name, meaning that it needs to be compiled.
In VS Code I don't find anything similar, with the result of not knowing when a class is saved or not.
Thanks

**Comment by isc-bsaviano** [comment]
@gbertolottiKS When you’re using server-side editing (which I assume you are based on your subsequent issue) the files are always saved on the server and by default they are compiled. If you turn off the compilation step (using the `objectscript.compileOnSave` setting) then yes there is no way to tell if the text you are seeing has been compiled or not.  Since we only have a one-way connection, there’s no way to know if someone else compiles the document on the server or if they delete the compiled code without polling for the information, which is expensive and not worth it for this feature in my opinion. @gjsjohnmurray what do you think?

**Comment by gjsjohnmurray** [comment]
I'm not convinced this is worth implementing, at least not unless/until we get more requests for it. Do many people operate in a mode where they save code changes to a server namespace without wanting immediate compilation?
