### ISSUE TITLE
Can't open server-side-only items for editing using ObjectScript Explorer since updating to v2.4.2.

### ISSUE THREAD

**Issue by isc-jsmith** [intersystems-community/vscode-objectscript#1068]
Type: <b>Bug</b>

Since updating to 2.4.2 I am unable to open server side items when working in a local workspace. The output window displays an isfs link and does not open the item.

For example in the following connection if I try to open MSNotification.Transform.Test.cls I get the following output in VSCode:
isfs://musical-octo-pancake/MSNotification/Transform/Test.cls?ns=PANCAKE
<img width="580" alt="Screen Shot 2023-02-02 at 3 14 32 pm" src="https://user-images.githubusercontent.com/76028226/216237603-ab1ea332-c396-440b-9fe6-b3ebbe92b6ca.png">

Extension version: 2.4.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Sorry about this. It happens when `"objectscript.serverSideEditing": true` and was caused by a late change in PR #1064.

As an expedient measure I have reverted the faulty part of that PR (see #1069).

@isc-jsmith please verify #1069 will resolve your problem. To do this immediately, download the zip at https://github.com/intersystems-community/vscode-objectscript/suites/10730663549/artifacts/538101517, extract the dev-1069 VSIX and install that.

All affected users: until 2.4.3 gets published please roll back to 2.4.1. Here's one way:

![image](https://user-images.githubusercontent.com/6726799/216253432-f4c1ca4b-32dd-44ce-a03f-5e68b4fb8b61.png)

If you are using proposed API (server-side search etc) you will need [2.4.2-beta-1](https://github.com/intersystems-community/vscode-objectscript/releases/tag/v2.4.2-beta.1) instead.

**Comment by isc-jsmith** [comment]
Just tried it and it looks good to me. Thanks for sorting it so quickly.

**Comment by gjsjohnmurray** [comment]
Thanks for the confirmation. Reopening this issue until 2.4.3 ships.
