### ISSUE TITLE
def1arg macro arguments - Expand to see how arguments are resolved for int code

### ISSUE THREAD

**Issue by alexatwoodhead** [intersystems-community/vscode-objectscript#1126]
Consider the macro
#def1arg MyGlobal(%subkeys) ^Data(%subkeys)

The code:
set $$$MyGlobal(K1,K2,K3)="abc"

is expanded in int code to:
set ^Data(K1,K2,K3)="abc"

However when hovering the mouse over the macro in class definition
The expression: $$$MyGlobal(K1,K2,K3)
Shows as: ^Data(%subkeys)
Instead of: ^Data(K1,K2,K3)

Its the same behavior with Studio as VSCode but would be more intuitive to expand the arguments.

![image](https://user-images.githubusercontent.com/691812/228616102-bc368f1f-0681-4300-960a-215e4f7e01ef.png)

**Comment by isc-bsaviano** [comment]
@alexatwoodhead The hover support is implemented by the Language Server extension. I can take a look to see if there's anything we can do in VS Code to improve this. However, since it's the same behavior as Studio I'm assuming the server-side code that does the macro expansion is what needs updating.

**Comment by isc-bsaviano** [comment]
@alexatwoodhead I opened an enhancement request on the Language Server GitHub for this issue: https://github.com/intersystems/language-server/issues/272
