### ISSUE TITLE
In some circumstances, closing an INT routine that has been changed, and choosing "Don't Save", causes the routine to briefly close and then re-open.

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#1130]
I observed this behavior after making several attempts to step through some INT code for a class (opened using Edit Other) that I had edited for debugging purposes. I am doing client-side editing. After my attempts, I removed my changes (thereby assuming that the file was now the same as the server version. I probably also recompiled the class. When I tried to close the INT file, I got the "Save/Don't Save/Cancel" dialog, and selected "Don't Save." The file closed, and then immediately re-opened. Repeating the same choices resulted in the same behavior.

After showing what was happening to @isc-bsaviano, I selected "Save" and got a dialog about "Versions don't match. Compare..." which showed me that the local copy of the file was actually very different than the server copy. I chose to save the server version and the file finally closed.

Brett was able to recreate this on his machine. Possible solution for this is when using client-side editing, choosing "Edit Other" automatically does the export to the client of the INT file.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray @isc-rsingh This bug only occurs when using the `Edit Other` option while editing client-side. We could try fixing the bug and keeping he current behavior of allowing client-side users to edit an `isfs` file, but I much prefer changing the command to export the "other" file to the local workspace folder, then opening it in the editor. That would strengthen the distinction between client-side and server-side editing, like #1115. I also think we should hide the `Edit Other` option for server-side folders, since it's redundant. What do you think?

**Comment by isc-bsaviano** [comment]
Joel and I haven't been able to reproduce this since it first came up
