### ISSUE TITLE
Server side search not working after update

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1131]
Hi.
Now that I have the last extension version (2.8.0), the server side search doesn't work anymore.
For example, I made the same search in VSCode and in Studio, and these are the results:
![immagine](https://user-images.githubusercontent.com/115481064/230382695-281ef730-3aff-4347-a3c3-4176c815e69a.png)

![immagine](https://user-images.githubusercontent.com/115481064/230382469-80123ffb-06fc-4eb2-9050-cec151922736.png)

I have the "intersystems-community.vscode-objectscript version 2.8.1-beta.1 activating with proposed APIs available."

Thanks in advance

**Comment by isc-bsaviano** [comment]
@gbertolottiKS Without seeing the JSON response, this is going to be hard to debug. Since your web server is suppressing the JSON responses for error HTTP status codes, can you try using the Web Gateway's [HTTP Trace](https://docs.intersystems.com/irislatest/csp/docbook/DocBook.UI.Page.cls?KEY=GCGI_monitor#GCGI_viewtrace) facility to capture the response packets?

**Comment by gbertolottiKS** [comment]
Sorry, I made by myself a mistake, all work😅
Just a curiosity: should I install the new beta vsix every time the extension updates?

**Comment by isc-bsaviano** [comment]
No problem, I'm glad it's working! If you want to use the server-side searching and quick open then yes you will need to download a new beta vsix from GitHub after each update. The VS Code team knows that we and others want to see those API's finalized so hopefully in the near future that won't be required!
