### ISSUE TITLE
No offline mode anymore?

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#1148]
So, there is no way to work offline with objectscript project?
Like, I open a project, don't have a running server, and need to just observe the code navigate by classes, but I see that Language Server is now a hard requirement, and it just logs errors that it can't access API, even if I just turned off the connection.

Why the connection is a requirement, even if I need to navigate to class in the same project?

**Comment by isc-bsaviano** [comment]
The Language Server is not a "hard requirement", and even if it's installed it will still provide value without a server connection (syntax coloring, folding ranges, document symbols etc).

**Comment by daimor** [comment]
Offline navigation was implemented in this extension, but was replaced with Language Server, which does not support it.

**Comment by isc-bsaviano** [comment]
Yes, the Language Server does require a connection for go to definition currently. Working offline was not something we prioritized when building it since the vast majority of users will have a connection and our past IDEs required it. I can look into supporting go to definition without a server connection.

**Comment by isc-bsaviano** [comment]
Closing in favor of the Language Server repo issue

**Comment by daimor** [comment]
thanks. it works now
