### ISSUE TITLE
revisit support export/import xml

### ISSUE THREAD

**Issue by isc-lindensc** [intersystems-community/vscode-objectscript#1158]
Hi All,
with the deprecation of InterSystems Studio, can we look into getting export/import of xml packaged source code implemented?

As a developer i often have the issue that i need to transport code from e.g. a non CCR controlled scratch environment to the BASE environment which then is under CCR source control.

This usually is done via ISC Studio export/import functionality.
ISC Studio import functionality also triggers the question on source controlled environment to add all imported code to source control (here CCR).

Using UDL as the export format can be prohibitive if the code consists of multiple classes/routines in multiple packages. (e.g. InterSystems Integration projects)

Also the current export functionality is rather clunky in large namespaces (i.e. thousands of classes) and also i found a bit hit and miss in regards to it working (got it working 2 out of 10 tries, usually not working when i try to present the functionality to others)

**Comment by gjsjohnmurray** [comment]
Have you evaluated the current UI for Projects? Perhaps adding command to export a project's members to a single XML file would help you.

**Comment by isc-bsaviano** [comment]
@isc-lindensc Even if we revisited the policy, I don't think the Atelier API supports getting multiple documents in a single XML file. I think the best approach is to use `$SYSTEM.OBJ.Export` from a terminal. You could even use our new WebSocket Terminal if you have the most recent beta version of this extension and a 2023.2 IRIS kit.

**Comment by isc-tleavitt** [comment]
I'd love to have support for this for the same use case(s). Can confirm after a quick look that we'd need new API endpoints for it to work properly though.

**Comment by isc-lindensc** [comment]
@isc-bsaviano yes agreed we need probably an API extension for the multi file export. But same priority is a dedicated "import file to server" function based on formats UML and xml especially for server side editing, which is the default usage scenario for TC devs and TC customers.

**Comment by isc-bsaviano** [comment]
@isc-lindensc That command has existed since January, see #1036. It only works for UDL files though and if we were to support XML files I'd probably create a separate command so that it works for client-side editing as well.

**Comment by isc-tleavitt** [comment]
@isc-bsaviano I think the specific use case to consider would be:
In isfs mode, export a multiple selection of items to XML. (Because that's the only way to export multiple items to a single file at this point.)
In isfs mode, provide a way to import an XML file containing multiple items (rather than e.g. using existing APIs to convert to UDL); import should trigger activity in %SourceControl same as it does in Studio.

Studio makes this super easy. You can even just drag and drop an XML export of multiple classes into Studio and it'll import them and do all the source control stuff.

**Comment by isc-tleavitt** [comment]
@isc-bsaviano it'll prompt to check out, I don't think to add (with %Studio.SourceControl.ISC, that is).

The behavior is all based on the extension though - see https://docs.intersystems.com/irislatest/csp/documatic/%25CSP.Documatic.cls?LIBRARY=%25SYS&CLASSNAME=%25Studio.Extension.Base#UserAction , "6 : User has selected to import comma delimetered [sic] list of documents"

**Comment by isc-lindensc** [comment]
> @isc-lindensc That command has existed since January, see #1036. It only works for UDL files though and if we were to support XML files I'd probably create a separate command so that it works for client-side editing as well.

@isc-bsaviano This is great, i did not know that its available for UDL. 

From a ease of use side could we also include a short-cut to the export for UDL on isfs folders: e.g. "Export to local filesystem" which then prompts with a save dialog?

**Comment by isc-bsaviano** [comment]
@isc-lindensc Feel free to open a new issue to request that feature. 

As for the XML import/export, I spoke to @isc-rsingh yesterday and we agreed to leave this open and gather more feedback before deciding what to do. The Atelier API was not designed for bulk import/export (the UDL command I added makes a bunch of REST requests and probably shouldn't be used on more than a handful of files at once). Since there are also other perfectly fine tools for this task we don't consider it a "must-add" at this time, but we are open to feedback that would change our perspective.
