### ISSUE TITLE
Highlighting of zWrite warns variable not defined

### ISSUE THREAD

**Issue by isc-aray** [intersystems-community/vscode-objectscript#1179]
The `zWrite` command prints the contents of a variable and any of its subscripts. It will never produce an `<UNDEFINED>` error, even if given a variable that is not defined and has no subscripts. Thus running the following method will never produce an error in ordinary circumstances:

``` objectscript
ClassMethod ZWriteIsSafe()
{
    Set myTest1="TEST"
    zWrite myTest1

    Set myTest2("subscript")="TEST"
    zWrite myTest2

    zWrite myTest3
}
```

However, the second and third cases produce "Local variable may be undefined" in VSCode:
![image](https://github.com/intersystems-community/vscode-objectscript/assets/43610734/2f112cce-83f5-426b-b580-c9b19be1ff5a)

**Proposed solution:** The highlighter should not check whether the argument(s) to `zWrite` are defined.

**Comment by isc-bsaviano** [comment]
The "variable may be undefined" warnings are coming from the Language Server, specifically the variable tracking feature of the ObjectScript parser. It only tracks sets and kills, and it only cares about the "root" value. As designed, this is not a bug since "myTest2" and "myTest3" are undefined. The tracking doesn't know about what you're using the variable for, and its`defined/undefined status doesn't change based on how its used.
