### ISSUE TITLE
Using webgateway-nginx to replace the PWS

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#1184]
Dear community,

I'm currently struggling to get NGINX configured to provide WebSockets for the VS Code debugging feature.
We're using the webgateway-nginx container with TLS 1.2 enabled as a starting point to replace the private web server of IRIS. And after my initial fail (https://github.com/intersystems-community/vscode-objectscript/issues/1178) to save classes, we now came across the issue that debugging doesn't work because NGINX needs special configuration to proxy the request to the CSP NSD module.

Neither of these location definitions let me start the WebSocket session:

```java
## VS Code access
location /api/atelier {
    CSP On;
    CSPNSD_pass 127.0.0.1:7038;
    CSPNSD_response_headers_maxsize 8k;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade" ;
}

location /api/atelier/v5/%SYS/debug {
    ## 2023-07-17 SeH Test just as proxy for WebSocket support
    proxy_pass http://127.0.0.1:7038;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
``` 

In the meantime I also tried to vary this as "CSPNSD_set_header" in the /api/atelier definition as well but that's not allowed in the configuration and let the NGINX fail to start.

This issue is opened to supplement [WRC#976799](https://wrc.intersystems.com/wrc/eucustprob2.csp?OBJID=976799) with the request to build comprehensive documentation how to configure NGINX at least to support the IRIS internal features (Management Portal, VS Code etc.)

Best regards,
Sebastian

_Originally posted by @S-Hahne in https://github.com/intersystems-community/vscode-objectscript/issues/773#issuecomment-1640056665_

**Comment by isc-bsaviano** [comment]
Hi @S-Hahne. I looked through your linked WRC case. The correct place for this request is in our internal system because it's requesting a change to InterSystems documentation (specifically the CGI_win_nginx page). Our VS Code docs are also moving to the [official InterSystems documentation site](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO), with that transition almost complete. I will leave this issue open so other community members can see it and offer help but unfortunate I'm not an expert at setting up web servers or nginx specifically.

**Comment by isc-bsaviano** [comment]
@S-Hahne I'm going to close this issue since it's being worked on internally by our docs team and isn't an issue with this extension. If you have questions about the status of that work you can ask the support advisor assigned to your WRC case.
