### ISSUE TITLE
Serverside editing changes does not reflect changes in source control

### ISSUE THREAD

**Issue by ltjand** [intersystems-community/vscode-objectscript#1192]
Type: <b>Bug</b>

I have set up serverside editing and able open a local repo branch, but when i make a change on the server, the changes are not reflected in the source control icon.  It's not telling me that i made a change that needs to be checked in.  It's acting like i have no SC...
I'm using vscode vers 1.75.1.  It was working using the 'serverside editing=true' option before, but something happened when i switched nampespace, and it messed up my login.  Now it seems to be ignoring that option.  So instead, i followed the instruction https://intersystems-community.github.io/vscode-objectscript/serverside/ to setup up editing, and then I hit shft-cntrl-P and typed "open repo", point to my repo folder.  This open my local repo, I also tried initializing a new repo, but none of it seems to connect my serverside changes to the source control...

Btw, I am not using github, I'm using devops on azure.

Thank you,
Lena

Extension version: 1.0.3
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.81GB (11.20GB free)|
|Process Argv|--crash-reporter-id 09d15bce-64f6-4a5e-a69b-f6f1abea8e0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30795824
dsvsc013:30795093

```

</details>

**Comment by isc-bsaviano** [comment]
@ltjand We removed that setting in the most recent version (2.10.0). The reasoning can be found in #1115. Can you explain your desired workflow a little better please? If you want to use server-side source control then you must use [server-side editing](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_ssworkflow).

**Comment by isc-bsaviano** [comment]
Hi @ltjand, I don't know what the "open repository" command is. Can provide a few screenshots of what you're doing? If you're using a `.code-workspace` file, can you provide the contents of that as well? I want to understand your setup better before I provide advice.

**Comment by ltjand** [comment]
Hi Brett,

I read the #1115<https://urldefense.com/v3/__https:/github.com/intersystems-community/vscode-objectscript/issues/1115__;!!G1p3e_M!bl-FvKzH5Uh3xGolAq_hWR_6YK6IZRLiMLyb4KG2_xBXPHf5CODfi06IZP2MutgSpBDHzTJd_hs-geyrChyewvipAQ$>, but I am still confused what the difference is?  I thought this change would allow server-side edit to also trigger updates to the client side source control… it doesn’t sound like that is the case?

So, what is the difference between the settings and the new change?  I did notice that I used to be able to make changes in the objectscript view, but now I can only make changes in the ‘intersystems tools’ view…  Either way, it still does not trigger an update to my local repository.  If this is still the case that’s fine, I just need to know that I move on.

***@***.***

Now, I can only make changes from here: what is the difference?  Aren’t they both changing the server code?
***@***.***

Thank you,
Lena

**Comment by isc-bsaviano** [comment]
Hi @ltjand, I just spoke to Gabriel, the support advisor on your WRC ticket, about your workflow. I think I understand it better now. Since you're using client-side source control, you should be editing the local copy of the files that are in the [VS Code file explorer](https://code.visualstudio.com/docs/getstarted/userinterface#_explorer). If you have a [server connection configured](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_config), any InterSystems files that you edit will be saved and compiled on the server when you save them. Since you edited the local files, you will be able to see the changes in your client-side source control system. If you're using Git based source control, VS Code will show you changes in its [source control view](https://code.visualstudio.com/docs/sourcecontrol/overview).

**Comment by ltjand** [comment]
Hi Brett,

What if I want it to work like before… ie, be able to edit server code, and still have my repo opened in my workspace ? (I understand that it won’t update my repo until I export out the code)

I was how my env was setup before, but I can’t seem to save the workspace so that next time I open vscode it’s still setup the same way – ie, with server side edit and my repo opened in the status bar:


  1.  I setup serverside edit: (noticed the status shows ***@***.*** , which indicates serverside edit is turned on


***@***.***


  1.  Then I select ‘open repository’ and select my folder: (note that you can see my repo and server-side edit)


***@***.***


***@***.***


  1.  The problem is how do I save my environment this way so next time I open vscode, it shows the same thing?  Right now, when I save workspace and come back in, it never open my repo.  I have to keep select ‘open repository’ to add it in…  If I choose open folder from the file menu, it gets rid of my serverside edit.  If I choose add folder to my workspace, it only lets me select the server path, and not my local folder path.

Can this be done? If so, how?

Thank you,
Lena

**Comment by isc-bsaviano** [comment]
Hi @ltjand, I can't see the images/files you're attempting to attach to your comment. Can you comment through GitHub instead of email so those can be shared? If they contain sensitive information you can post them on your original WRC ticket and I will be able to see them. Based on just your comment, I think you have an unsaved workspace and are exiting before saving it. To save it, open the File menu and select the "Save Workspace As..." option. You will be prompted to save a `.code-workspace` file that defined your workspace. You can then open it to continue where you left off.

The workflow you are describing is not explicitly supported by this extension because it allows for edits that may not make it back to your source control system (if you forget to export certain files later, for example). I recommend that you always edit the local copies of the files in your source control repository. The ObjectScript Explorer can still be used to view other files and will open your editable local copy if it exists.

**Comment by ltjand** [comment]
Hi Brett,

I did try saving the workspace before I quit but same problem.  You may be looking at a snapshot of what I was trying to recreate for your benefit.  Anyway, don’t worry about it – I will do as you suggest…

Thanks anyway,
Lena

**Comment by isc-bsaviano** [comment]
When you go to re-open the workspace, are you clicking on the code-workspace file that you just saved or are you opening the local folder again? If it's the latter then that's why you're losing the other root folder that you added.

**Comment by ltjand** [comment]
I have tried a number of things including:
- opening the workspace from file – it will open my workspace, but I only see the server-side edit icon, but not my repo icon
- Again, I tried to ‘open repository’ then save my workspace again, still when I quit and come back in, I only see the server-side edit icon and not my repository icon.  If I open folder instead, it will remove my server-side edit icon, and I only see the repository icon- which means I can’t make server-side edits…

Anyway, I have given up.  You can close the case.

Thank you,
Lena

**Comment by isc-bsaviano** [comment]
Closing as per the last comment
