### ISSUE TITLE
JWT Authentication

### ISSUE THREAD

**Issue by daimor** [intersystems-community/vscode-objectscript#1194]
I'm recently noticed an update in Web Applications, there was added JWT Authentication
I did not play with it, and not sure, how to properly configure it

<img width="586" alt="image" src="https://github.com/intersystems-community/vscode-objectscript/assets/1212251/7750a21f-e9e1-404e-8da9-74edd3b880fa">

Could it be implemented here too?
Some customers I suppose would like to have it as an option

`IRIS for UNIX (Ubuntu Server LTS for ARM64 Containers) 2023.2 (Build 201U) Mon May 15 2023 10:40:01 EDT [Health:5.1.1]`

**Comment by isc-bsaviano** [comment]
@daimor I've spoken about this to people internally. JWT doesn't offer more security, it's just a different method of storing the authentication information. Since we need to support old servers that don't have that support, I don't think it's worth the effort and complexity to move to JWT without a clear reason or pressure from another team in ISC.

**Comment by daimor** [comment]
I did not mean move to JWT, I mean as an option, depending which way is activated on the server.

**Comment by isc-bsaviano** [comment]
Yes, we would need to keep supporting session cookies no matter what. I can ask the people who implemented JWT support but my understanding is that JWT doesn't buy us anything security-wise.

**Comment by isc-bsaviano** [comment]
I consulted the security team and moving to JWT for future releases doesn't make the application more secure. We're going to hold off on making the server-side change until there's a compelling reason to do so.
