### ISSUE TITLE
Improve Intellisense context awareness

### ISSUE THREAD

**Issue by baasvancodeza** [intersystems-community/vscode-objectscript#1287]
## Irrelevant Code Completion suggestion
Example:  
I have a class containing a Property named MasterRecord  
There is an Include file named MasterLibDefs  
I create an instance of the class.  
When typing Set tObj.Mast it brings up MasterLibDefs first in the list of completion options which is completely irrelevant.

## No List of Properties or Methods
In studio when typing in ##class with a class name followed by ). then it would bring up all the possible options relevant to the class immediately.  
Also, after creating a class instance and typing set tObj. it would bring up all the properties and methods immediately.  
  
Sometimes the code completion works more against you than for you. Studio's code completion is still better, but Studio support is being dropped soon as far as I know.

**Comment by isc-solon** [comment]
Others can confirm this, but if Code Completion is suggesting the name of an include file, you're **not** seeing IRIS code completion suggestions, which are preceded by a little wrench icon (for properties) or box icon (for methods). Instead, you're seeing the VS Code "text from elsewhere in the class" suggestions, which are preceded by a little "abc" icon. This usually happens if VS Code is not connected to the server, or if there's something not quite right with the connection. On my system, if I disconnect from the server, I see what you're seeing. But if I'm connected, I never see a suggestion for the name of the include file. That would also explain your other 2 examples. When properly connected, both ")." and "tObj." bring up a list of valid suggestions.

**Comment by baasvancodeza** [comment]
Thank you for the information. I will look in a bit more detail at it.

**Comment by isc-bsaviano** [comment]
@baasvancodeza Without more information or a screenshot, I think that Joel correctly diagnoses the problem.

**Comment by isc-bsaviano** [comment]
@baasvancodeza I'm going to close this because I don't think there's a bug here but if you're still having issues please re-open and Ill try to help.
