### ISSUE TITLE
SQL Privilege errors in V.1.12.0-beta.8

### ISSUE THREAD

**Issue by S-Hahne** [intersystems-community/vscode-objectscript#1306]
Dear team,

I was just made aware that we're getting the following messages from the ObjectScript extension since the automatic update to 1.12.0 today:
`ERROR #5540: SQLCODE: -99 Message: User <username hidden> is not privileged for the operation`

I tracked this behaviour to have changed between 2.12.0-beta.7 and -beta.8
Hopefully the changes are small enough to track the issue without much effort.

Does anyone know the SQL privileges that are now required to work with the extension? Our server is locked down, so we will most likely need to add some rights to the %Developer role again.

Best regards,
Sebastian

**Comment by isc-bsaviano** [comment]
@S-Hahne Thanks for the version information. What operations are you doing when the error occurs?

**Comment by isc-bsaviano** [comment]
The most important query to have permission on is [StudioOpenDialog](Also, if you upgrade to IRIS 2021.1.3+, 2022.1.1+ or 2022.2+ you shouldn't get SQL permissions errors due to a server-side bug fix. The most important query to ), but that's not new for this version. Are you using server-side editing or client-side editing? Also, Ii you upgrade to IRIS 2021.1.3+, 2022.1.1+ or 2022.2+ you shouldn't get SQL permissions errors due to a server-side bug fix.

**Comment by isc-bsaviano** [comment]
@S-Hahne What version of IRIS are you connected to? Yes, that query was added but I'm not sure why it's being run if you have a server version old enough to report these permissions errors. That unit test code should only be run if your server is 2023.3 or newer. If it's running for all servers then there's a bug that I need to fix.

**Comment by isc-bsaviano** [comment]
@S-Hahne Can you please download and install the vsix found [here](https://github.com/intersystems-community/vscode-objectscript/actions/runs/7712011454/artifacts/1205625066)? This should fix your issue.

**Comment by isc-bsaviano** [comment]
Thanks for testing! I'm glad the fix worked. This issue will close automatically when the pull request is merged. The version will almost certainly be 2.12.1-beta.2
