### ISSUE TITLE
Updating a Project does not update last update date

### ISSUE THREAD

**Issue by gbertolottiKS** [intersystems-community/vscode-objectscript#1335]
Hi.

We've noticed that creating a new Project using VS Code does not set the last update date, and modifying an existing one (e.g. adding a new class) does not update the last update date.

Thanks in advance.

**Comment by isc-bsaviano** [comment]
This is intentional. VS Code only touches the fields that it cares about. Since we treat projects a collection of documents/folders and ask the server for contents whenever we need to, there's no need for us to care about that timestamp. Why is it necessary that we update it? Source control reasons?

**Comment by gbertolottiKS** [comment]
Yes, of course, I try it asap, and I'll let you know, thanks

**Comment by gbertolottiKS** [comment]
It works, thanks!
