### ISSUE TITLE
Find in files Error

### ISSUE THREAD

**Issue by spotashn** [intersystems-community/vscode-objectscript#1354]
Since upgrading an environment to 2023.1.1 the find in files functionality no longer works

Iris Implementation: IRIS for UNIX (Red Hat Enterprise Linux 8 for x86-64) 2023.1.1 (Build 380_0_22870U) [Health:3.5.0]

Log :
intersystems-community.vscode-objectscript version 2.12.4-beta.4 activating with proposed APIs available.
ERROR #5002: ObjectScript error: &lt;MAXSTRING&gt;FindInFilesAtelierv6+46^%Studio.Project.1

**Comment by isc-bsaviano** [comment]
@spotashn Thanks for reporting this. Would it be possible for you to get a network trace using Wireshark or the web gateway's [HTTP trace tool](https://docs.intersystems.com/iris20241/csp/docbook/DocBook.UI.Page.cls?KEY=GCGI_monitor#GCGI_viewtrace)? The <MAXSTRING> is due to a $LIST of document names being over the max string length. Are you searching a large number of classes/routines with very long names?

**Comment by gjsjohnmurray** [comment]
Perhaps a Project containing a very large number of classes / routines?

**Comment by isc-bsaviano** [comment]
It could be that too, but the list would have to be huge.

**Comment by isc-bsaviano** [comment]
@spotashn Since this is a bug in IRIS I will fix this internally. Closing.
