### ISSUE TITLE
Templates for Interoperability Messgages

### ISSUE THREAD

**Issue by mmassias** [intersystems-community/vscode-objectscript#1403]
Hi,
I can see templates for Business Services, Business Operations and so on, but none for Messages, i.e. subclasses of Ens.Request and Ens.Response. Is there any intention to provide this?

Many thanks,

Mark

**Comment by isc-bsaviano** [comment]
@mmassias We might be able to provide something like that. What information would you expect it to collect?

**Comment by isc-bsaviano** [comment]
@mmassias I looked at what the Studio wizard for creating a new message does. Since all it does is select the right superclass and let you add properties, I don't think it's worth creating a new one here. I'll leave this issue open for a little while to see if anyone else request this. Maybe consider promoting this on the Developer Community.

**Comment by isc-bsaviano** [comment]
This doesn't seem to be worth the effort
