### ISSUE TITLE
Routine Header line

### ISSUE THREAD

**Issue by svetozarstojkovic** [intersystems-community/vscode-objectscript#1455]
Hello,

We are trying to use client side editing version of the extension but as we have couple thousand routines that do not have header at the beginning of routines, so when I try to compile the routine I am getting the error: 
![image](https://github.com/user-attachments/assets/8e60e26e-0ca1-44bd-af5f-b6a1c6ea47e7)

Is there maybe some easy way to skip this check and skip it based on some flag or something while compiling or we need to add this header to all 4000 routines?

Thank you in advance,
Svetozar

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic The Atelier REST API that VS Code uses to communicate with the server requires the ROUTINE header. The syntax is pretty simple: 

```
ROUTINE <name> [Type=<extension>,Generated,LanguageMode=<language_mode>]
```

Where <name> is the name of the routine in the server without the file extension, and <extension> is the file extension in all caps. The routine Type is MAC by default. Your routines probably aren't generated, so that keyword shouldn't be present. <language_mode> defaults to 0 for ObjectScript and it's very unlikely that you'd be using a different one, so that can be left out as well.

Assuming the file system path and names of the routine files on disk matches the routine name in some way, it should be easy to write a script that does this for you. The Language Server should provide a problem squiggle at the top of the file if it's opened that alerts you that a header is missing and provides a "Quick Fix" to add it for you. There's an open ticket for documenting this header, I will link this issue to it and bump the priority.

**Comment by isc-bsaviano** [comment]
@svetozarstojkovic Were you able to add the header? I'm still surprised you had MAC and INT routines on disk without the header.

**Comment by isc-bsaviano** [comment]
Closing because there isn't a defect with this extension

**Comment by svetozarstojkovic** [comment]
@isc-bsaviano 

Hello, We decided that we will move in a direction that you suggested - to add ROUTINE to the start of every routine.

The reason why we don't have it is that we used some third company tool for exporting/importing files and that tool only copied the content of the files, it didn't use the atelier endpoints.

But now I am trying to push the management to start using atelier as it should be used and I trying to make it work with as small number of changes so they would accept it.

Thank you guys for answering to my every question however stupid it might sound to you 😄
