### ISSUE TITLE
Code format should not change when compiled

### ISSUE THREAD

**Issue by isc-aray** [intersystems-community/vscode-objectscript#194]
If I have a method with a very long spec, I will often write it on more than one line, for example:

``` objectscript
ClassMethod WithAVeryLongSpecification(
    ByRef each As %String,
    argument As %Boolean,
    on As %Integer,
    ByRef its As %Status,
    ByRef own As %Double,
    Output line As %Stream.FileBinary
) As %Status {
    ;; implementaton
}
```

And this is highlighted almost correctly by the parser:

![image](https://user-images.githubusercontent.com/43610734/87171226-013fd700-c298-11ea-8dc5-333afc7d357e.png)

But when I compile it, the editor collapses it to one line:

``` objectscript
ClassMethod WithAVeryLongSpecification(ByRef each As %String, argument As %Boolean, on As %Integer, ByRef its As %Status, ByRef own As %Double, Output line As %Stream.FileBinary) As %Status
{
    ;; implementaton
}
```

This means I can't see the whole spec without scrolling the window horizontally.

![image](https://user-images.githubusercontent.com/43610734/87171360-2fbdb200-c298-11ea-98a8-83810e2fa231.png)

The editor should _never_ take it upon itself to reformat my code unless I ask it to.

**Comment by vsfan** [comment]
hmm, I forgot the behavior of the studio - which I think it does something similar.

**Comment by aray-isc** [comment]
@vsfan Studio indeed has similar behavior of reformatting (but has an option to put each argument on a separate line) because it communicates with the server using XML (which does not preserve the UDL structure) and does not retain a local copy of the class. Atelier has the behavior I describe of leaving the UDL structure as written, which IMO is much nicer. At least I would like an option to chose one behavior or the other.

**Comment by daimor** [comment]
Yeah, it's a known issue, happens due to the necessity of updating some other parts of the class, which was changed on the server. The simplest thing is default Storage definition for stored classes when properties changed. Or it can be changed with SourceControl class. I don't know how Atelier managed to deal with it, so, I'll need some time on investigation, how to keep the original formatting.

**Comment by gjsjohnmurray** [comment]
ping @isc-jamien

**Comment by isc-jamien** [comment]
Atelier dealt with this issue by an extremely complicated and error-prone merging process which led to many problems. We don't want to repeat that experience with VS Code. On compilation the server will canonicalize the sources, adding any storage required. This is by design. There is the possibility of exposing the option to format the method arguments as multiline which we will look into.

**Comment by gjsjohnmurray** [comment]
See also #101

**Comment by gjsjohnmurray** [comment]
> There is the possibility of exposing the option to format the method arguments as multiline which we will look into

Adding 'upstream' label because this would require a server-side change.

@isc-jamien has anything been prodlogged?

**Comment by UltraMed** [comment]
I second the opinion that source code formatting should be maintained as it is in Atelier. The editor shouldn't reformat my code if it is a valid syntax. I like to put the arguments on separate lines for methods for readability. I can't switch off of Atelier to VS Code until this is fixed.

**Comment by isc-jamien** [comment]
We will not be making this change, this is a non-negociable requirement of the implementation as discussed above.

**Comment by UltraMed** [comment]
isc-jamien said:
"There is the possibility of exposing the option to format the method arguments as multiline which we will look into." 

So when we will know about this? It's simply not acceptable for me the way it is.

**Comment by isc-jamien** [comment]
@isc-aray please consider logging an enhancement request just for multi-line method arguments. That is something we CAN implement simply.

**Comment by isc-jamien** [comment]
@UltraMed please log as an enhancement. This will require an Atelier API change on the server but is eminently do-able
