### ISSUE TITLE
Multiple Server Connections

### ISSUE THREAD

**Issue by ndsmith3** [intersystems-community/vscode-objectscript#31]
My work is spread across several different Cache servers. Currently, I have to alter my settings to switch the connection I want to work on. I would like to see multiple different connections allowed in the extension.

**Comment by theflyingape** [comment]
I would not expect to have any VS code synchronization between multiple instances and a developer's workstation(s).  Use Caché ECP for that.  :sunglasses:

Can it allow its connection settings to support an _array_ of Caché instance profiles -- provide a **local** logical name (i.e., "My Local", "dev", "Test", "LIVE") with a required file path?  Those logical named label(s) could serve nicely as the top-level for the remote instance in its explorer.

I see the value here as having this in the User settings.json to simplify each developers' global profile within a single Code session, instead of making many "per workspace" profiles -- while that is doable, it loses appeal and operates much like the CStudio as another classic client/server app.  I'd like to see multiple & switchable configs with local (or remote!) profile support... something akin to [liximomo.sftp](https://marketplace.visualstudio.com/items?itemName=liximomo.sftp) extension.

**Comment by daimor** [comment]
It's not a problem to make it as an array of connections. I am just not sure how to deal with. 
But with multi-root workspaces from VSCode you can do it already, with editing on server as well. I can explain configs later when I will be not on phone.

**Comment by daimor** [comment]
I have added new repository with the example of using multiple connections at once.
https://github.com/caretdev/vscode-multi-connection
Just in case if somebody will find it useful

**Comment by bourette** [comment]
It would be useful if you showed your workspace definition for this example.
