### ISSUE TITLE
"View Other" should jump to the corresponding location in the "other" document

### ISSUE THREAD

**Issue by timleavitt** [intersystems-community/vscode-objectscript#363]
For parity with Studio, when you select "view other" it should jump to the place in the "other" document corresponding to the current cursor position, if one is defined.

This requires access to the debug map, which I don't know the availability of via Atelier APIs. (Currently investigating and may offer a PR if there's a straightforward solution.)

**Comment by timleavitt** [comment]
After some investigation, this looks like an upstream issue. Two good ways this could be addressed:
* An SQLProc wrapper for calling %Studio.Debugger:INTLine and %Studio.Debugger:SourceLine/MappedFromLine. (Likely a custom class query like those found in %Atelier.v1.Utils.General.) Advantage: covers exactly what we need in this case with one query.
* Supporting a "label" attribute on the /:namespace/action/index endpoint in the Atelier APIs and passing it to %Library.RoutineMgr:GetOther (which in turn calls INTLine/MappedFromLine). Advantage: we're already using this endpoint in "view others".

**Comment by isc-bsaviano** [comment]
This will be fixed in v4 of the Atelier APIs. From the devkey description:

To map the location in a document to the corresponding location in "other" documents (like the generated INT for a class), append the label+offset to the end of the document name separated by a colon (i.e. [ "%Activate.Enum.cls" ] becomes [ "%Activate.Enum.cls:method+5" ]) and all "other" documents in the response body will contain the document name and corresponding offset separated by a colon:
```json
"others": [
    "%Activate.Enum.1.INT:+11"
]
```
