### ISSUE TITLE
Source Control option "Discard All Changes" reported an error and no files were deleted

### ISSUE THREAD

**Issue by marykerins** [intersystems-community/vscode-objectscript#379]
In the Source Control Panel I used the undo symbol to "Discard All Changes".   A popup asked for confirmation to delete the files; I clicked the "Delete Files" button.  This error was reported: 
"Git: warning: failed to remove $GetCurrent/Logs/PartnerSetupCompleteResults.log: Invalid argument."
 No files were deleted.

**Comment by daimor** [comment]
How it's related to this extension?

**Comment by marykerins** [comment]
I don't know how it's related to the extension, I'm reporting what happened.  Here's a more complete picture:  I wanted to try Source Control.  I clicked the SC button and the panel asked if I wanted to initialize/authorize this action (not sure exactly what text was).  I opted to continue, and then got this message "The git repository at 'c:\' has too many active changes, only a subset of Git features will be enabled".   This is not what I wanted so I then tried to use the "Discard all changes" option.  There was a popup "Are you sure you want to DELETE 5000 files?", I selected the "Delete Files" button which gave me this error "Git:  warning: failed to remove $GetCurrent/Logs/PartnerSetupCompleteResult.log: Invalid argument".

**Comment by gjsjohnmurray** [comment]
@marykerins I don't yet understand exactly what you did. Here are a few questions. As well as answering them it'd be useful if you would recreate the issue and paste screenshots into your reply. On Windows you could use the Snipping Tool to copy a region to your clipboard. Then you can paste direct from there into your GitHub response using Ctrl+V.

My questions:

1. Did you start from an empty instance of VS Code (i.e. no file, folder or workspace open)?
2. By "I clicked the SC button" do you mean this:
![image](https://user-images.githubusercontent.com/6726799/96038634-4c512380-0e5f-11eb-97a1-a468a4ed52c1.png)
3. If so, what did you do next? Judging by the message you reported above, perhaps you clicked "Open Folder" and then picked the root of your C-drive.
4. Did you then get this, and click the "Initialize Repository" button?
![image](https://user-images.githubusercontent.com/6726799/96039074-06488f80-0e60-11eb-9bb0-f21e093e6d3a.png)
If so, you asked Git to create a repository capable of tracking **all** the files on your C-drive. That probably wasn't what you intended.
5. The popup you saw from VS Code when you clicked the "Discard All Changes" button attempted to warn you what was about to happen. Another VS Code user (not using it with InterSystems platforms) recently reported a similar scenario at https://github.com/microsoft/vscode/issues/108348 and as a consequence the next VS Code release will make that popup EVEN MORE EXPLICIT.

I do hope your actions didn't delete any files from your C-drive. But either way, the above steps are unrelated to the vscode-objectscript extension.

**Comment by marykerins** [comment]
@gjsjohnmurray  I will respond here as best I can.  I have some screenshots that I can share from the original report; however I cannot recreate all steps because I still have 5000 files sitting in SourceControl panel.  Below is a screenshot of what I have now; when I click the undo icon "Discard all changes", I get the error reported in the original issue:  
![image](https://user-images.githubusercontent.com/18037668/96041490-e8683400-0e39-11eb-8444-291bdaebd71b.png)

1. I did not start from an empty VSCode; I have a .code-workspace file, settings.json, and some class files.  At least some of these were open at the time.  
2. Yes, that is the button that I clicked; you should be able to see this in the screen shot above. 
3. You are correct. I picked "Open Folder"; I'm not sure if I picked my C: drive root.  Since my perforce workspace is set to c:\perforce, my guess is that I picked that directory.  Either that I accepted the default.
4. Yes, I clicked "Initialize Repository" button.  What I was trying to do was intialize Source Control, not create a repository with files on my C: drive.
5. Yes, the popup was correct; it asked me to confirm that I wanted to delete 5000 files.  I wanted to delete the files so I clicked "Delete Files" button.
![image](https://user-images.githubusercontent.com/18037668/96042846-0a62b600-0e3c-11eb-9643-75af940ae909.png)

After I clicked "Delete Files", this message was displayed:
![image](https://user-images.githubusercontent.com/18037668/96043062-66c5d580-0e3c-11eb-8091-774eff14680a.png)

First I clicked the "Cancel" button, no files were deleted so I think this just cancelled the delete action.
I tried again, and this time I clicked the "Open Git Log" button.  Nothing useful to me from this action and the files were not deleted.  Here's a screenshot of the beginning of the log:
![image](https://user-images.githubusercontent.com/18037668/96043517-156a1600-0e3d-11eb-8de7-446921096bf6.png)

So the issue for me is that I tried to do something and followed screen options that I thought were what I wanted.  When I realized I was wrong, I tried to use the option, "Discard all changes", to undo what I'd done, but this action is failing with an error about an invalid argument (see screen shot above). 

 Which popup will be more explicit?  The confirmation popup seems clear enough for my intensions right now.  The other popup reports an error that I think should be fixed, and it's the reason I entered this issue.  

A quick look at my C: drive looks to have all files intact, and I don't see 5000 extra files, although maybe I don't know where to look for them.   But now the bottom line for me is, how can I cancel the action and remove the files from my VSCode app :-)

**Comment by gjsjohnmurray** [comment]
@marykerins the dialog that will be more explicit in VS Code version 1.51 is the one you show in step 5. In addition to saying what it already does (`Are you sure you want to DELETE xxx files?`) it will in future add the following text:
```
This is IRREVERSIBLE!
These files will be FOREVER LOST.
```
You clearly didn't intend to delete 5000 files from your C drive. I think you narrowly avoided disaster only because the first (or at least a very early) file it tried to delete triggered an "invalid argument" error for some reason.

On my Windows 10 the first directory on the C drive is named $GetCurrent. Within that the first directory is called Logs. This contains three .log files, one being PartnerSetupCompleteResult.log.

To get out of your predicament I suggest these steps:
1. Close VS Code
2. In Windows Explorer delete the c:\.git directory which your step 4 created. It's likely to be a hidden directory, so you may have to change a Windows Explorer setting before you get to see it there.

Next time you start VS Code and it reopens the folder (c:\) that you were in the last time you closed it, the SCM view should revert to looking like my screenshot in step 2.

Notice that the text on that screenshot and the next one talks about the git source control tool. In your response you talked about Perforce, so perhaps you don't want to do anything git-related. VS Code is biased towards git in that it ships with git integration built-in (though you still have to install the git client software on your PC). VS Code's SCM view can also manage client-side files (i.e. files on your PC) using other SCM tools as long as an extension has been written to do this and you have installed that extension.

Are you already using Perforce as your SCM tool for working with InterSystems sources (classes, routines etc) via Studio or Atelier?

Is a server-side source control class involved, configured via Portal?

If so, maybe you should be using our extension's [Server-side Editing](https://intersystems-community.github.io/vscode-objectscript/serverside/) feature.

**Comment by marykerins** [comment]
@gjsjohnmurray First, I believe you are correct, I should be using server-side editing; I usually use Studio or Atelier with perforce.  But I still need to handle the 5M files.  I modified windows explorer view to show hidden files and empty directories; this did not show $GetCurrent on my C: drive (windows 10).  Ahh - I can see $GetCurrent from the cmd window with dir /ah.  So it is there.
    
If using the SourceControl button was an error on my part, and I am not and will not be using the git repository, why do you think I don't want to delete the 5M files?   That is what I was trying to do.  

Sorry for my confusion here, and thank you for your help with this.

**Comment by gjsjohnmurray** [comment]
@marykerins the 5000 files are local files on the C drive of your PC. I really don't think you want to do what is in effect a recursive delete of all files in c:\ and below, do you?

Instead, delete the c:\.git directory (note the leading dot/period on that folder name). It's probably a hidden folder. It and its contents were created by git when (via the VS Code button) you asked to initialize a repository for your entire c:\ filetree.

Once you have deleted that directory, VS Code will no longer show you 5000 files marked with the "U" (for Untracked) indicator. Instead it'll say you don't have a git repo in place to manage c:\

**Comment by marykerins** [comment]
@gjsjohnmurray  I followed your instructions above, and the 5M files are no longer indicated.  I definitely did NOT want to delete the entire c:\ tree, so very happy for the missing arg which seems to have saved me from disaster!   Thank you for your help getting this fixed.
