### ISSUE TITLE
When import entire package with many classes, many files show error: connect ECONNREFUSED 127.0.0.1:52773

### ISSUE THREAD

**Issue by pnguyenRCUS** [intersystems-community/vscode-objectscript#539]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue: When import entire package with many classes, many files show error: connect ECONNREFUSED 127.0.0.1:52773. If select only files with error,  and import again, no error. 

1. From VSCode Explorer, select entire src folder or package with many classes.
2. Right-click  and select Import without Compilation

Result: It starts importing but will show many error messages like below.
request to http://127.0.0.1:52773/api/atelier/ failed, reason: connect ECONNREFUSED 127.0.0.1:52773
Check your server details in Settings (127.0.0.1:52773[myns]).

![image](https://user-images.githubusercontent.com/26148445/103098823-092ed180-45c1-11eb-92b8-6ee29ffe28ec.png)

USER>w $zv
IRIS for Windows (x86-64) 2020.1 (Build 217_1U) Tue May 26 2020 20:41:06 EDT

Installed extensions version number:
![image](https://user-images.githubusercontent.com/26148445/103098659-6ece8e00-45c0-11eb-9eb7-95959c75a42c.png)

**Comment by daimor** [comment]
VSCode, not supposed to be used this way. It would be ok to import a few classes, but not large amounts of files.
It's an editor, not a deployment tool.

**Comment by pnguyenRCUS** [comment]
Hello @daimor, if my above operation is not to be used, could you please tell me how to get the code into my namespace after cloning a github repository? Thanks

**Comment by daimor** [comment]
Due to the design of InterSystems products. You need that newest version of code to be imported and compiled in the database. And no matter would you use VSCode or Studio. In ideal situation, it should be possible to call `$system.OBJ.LoadDir("path to your sources","ck")` which will rebuild entire project with the latest version of code stored in the folder. But it may not work, as simple, due to many reasons. Project too big, or issues in code need controlled compilation order. So, I have no simple way how to deal with it. It depends entirely on your project.

I personally prefer using docker, and I rebuild the entire environment when I change branches or getting new commits.

**Comment by pnguyenRCUS** [comment]
Thanks very much for your response and suggestion. Happy holidays.
