### ISSUE TITLE
Document all possible settings

### ISSUE THREAD

**Issue by isc-sshutov** [intersystems-community/vscode-objectscript#565]
We need a single document describing all possible settings and their syntax including but not limited to objectscript.conn, servers and isfs

**Comment by gjsjohnmurray** [comment]
@jstetson10 the definitions of the settings for this extension can be seen in the "configuration" subsection of the "contributes" section of its [`settings.json`](https://github.com/intersystems-community/vscode-objectscript/blob/master/package.json) file. At time of writing this comment that begins at line 633.

**Comment by jstetson10** [comment]
The content of the settings.json file is not always completely transparent. Additional input will be needed in some cases.

**Comment by isc-bsaviano** [comment]
@jstetson10 The `objectscript.format` settings only take effect when the Language Server extension is uninstalled or disabled due to feature overlap. It would be very helpful if your documentation mentioned that, and pointed users to the correct settings to change. For reference, I list all LS configuration settings [here](https://github.com/intersystems/language-server#language-feature-configuration).
