### ISSUE TITLE
Unable to navigate class hierarchy

### ISSUE THREAD

**Issue by isc-pchung** [intersystems-community/vscode-objectscript#584]
In an instantiated object having class hierarchy, VSCode can't navigate to method definitions.

Load the attached XML file with test class hierarchy, 

Inside test.ClassC.test(), trying to navigate to object method show message "No definition found .."

"Outline" of class structure also doesn't show inherited property/method. 

Though IntelliSense shows when typing, items in scope.

Seems VSCode can not handle navigating object methods.

[test_class_hierarchy.zip](https://github.com/intersystems-community/vscode-objectscript/files/6152014/test_class_hierarchy.zip)

**Comment by isc-bsaviano** [comment]
@isc-pchung The outline is only supposed to show class members in the currently open file (labels for routines, macro definitions for include files). This is the expected behavior and is consistent with how the outline works for other languages. 

For the other issue, the language server (which provides coloring, intellisense and a bunch of other features) does not do type inferencing. The only variables that we provide intellisense for are ones that are declared using `#Dim`, or are method parameters that have types. This is also the expected behavior.

**Comment by isc-pchung** [comment]
@isc-bsaviano Thanks. To confirm, how should developer navigate to method definition after instantiating an object?

**Comment by isc-bsaviano** [comment]
@isc-pchung If you want to use go to definition to do that, you need to declare the type of the variable using [`#Dim`](https://docs.intersystems.com/irislatest/csp/docbook/Doc.View.cls?KEY=GCOS_macros#GCOS_macros_mpp_lbDim) before you assign a value to it. Otherwise, you'd have to know what class the method comes from and open it yourself using the ObjectScript Explorer or isfs.

**Comment by isc-pchung** [comment]
Suggested approach didn't seem to work. 

Updated the object initialization to 

![image](https://user-images.githubusercontent.com/3238506/111801243-23680b00-88a3-11eb-8ca4-3db6a6d84418.png)

**Comment by isc-bsaviano** [comment]
@isc-pchung You need to give it a type:
```objectscript
#Dim obj As eisl.ClassC = ##class(eisl.ClassC).%New()
```

**Comment by isc-pchung** [comment]
Thanks @isc-bsaviano.
