### ISSUE TITLE
Find x as whole word does not accept _x_

### ISSUE THREAD

**Issue by MartinFukatko** [intersystems-community/vscode-objectscript#610]
Find x as whole word does not accept `_x_`
Example below result is "1 of 1" but should be "1 of 2" 
```
 Set x="aaa"
 Write "Test "_x_" xxx"
```

How to change every "x" variable to something else?

**Comment by gjsjohnmurray** [comment]
We're using standard VS Code behaviour here. I suggest you use a regular expression. Toggle this mode by using the button to the right of Find Whole Word.

**Comment by gjsjohnmurray** [comment]
I think the "Match Whole Word" button wraps what you enter with `\b` word boundary anchors and does a Javascript-type regex match.

Unfortunately the underscore isn't treated as a word boundary. https://stackoverflow.com/a/29068796 offers a solution, but it uses `\K` (called Match Reset), which VS Code can't handle (because it does Javascript regexes, not PCRE ones).

**Comment by isc-bsaviano** [comment]
@MartinFukatko The Language Server extension provides [symbol renaming](https://code.visualstudio.com/docs/editor/refactoring#_rename-symbol) support for ObjectScript local variables and method arguments within class definitions.

**Comment by MartinFukatko** [comment]
Solved. 
I've added underscore to VScode Settings editor.wordSeparators
Thank you all.
