### ISSUE TITLE
Documentation Enhancement Request: ISFS

### ISSUE THREAD

**Issue by michaelfortunato** [intersystems-community/vscode-objectscript#636]
## Documentation Recommendation for Server Side Editing section and Notes.ISFS subsection
1. Under subsection **More about isfs and isfs-readonly workspace folders**, give the full json for the workspace definition
This     
   ` {
    "folders": [
		{
			"name": "test:USER",
			"uri": "isfs://test:user/"
		}
	]
    }`  as opposed to this `{
			"name": "test:USER",
			"uri": "isfs://test:user/"
     }`
    a. Explicitly give the json example the header titled "example.workspace"
    ##### example.workspace 
    `{
	"folders": [
		{
                        "name": "test:USER",
			"uri": "isfs://test:user/"
		}
	]
    }`
2. I would also personally put this example right in the section **Server-side Editing**, rather than under **Notes**.
3. Would also be good to emphasize that the configuration needs to happen in your vscode workspace definition, not your user definition.
4. Under the section **Server-side Editing** include a screenshot of clicking the pencil icon, like this
![vscode-docu](https://user-images.githubusercontent.com/43207799/117184957-514bd500-ada7-11eb-952c-e7e722bed323.png)
, or have a screencast as done in the **Installation** section.

Thanks

**Comment by jstetson10** [comment]
Hi,

The server side editing documentation that I have prepared and continue to work on does not have a subsection titled: More about isfs and isfs-readonly workspace folders. So, I’m not really sure what you’re referring to. Can you send me a link to the content in question? Thanks,

j-


From: Michael Fortunato ***@***.***>
Sent: Wednesday, May 5, 2021 1:44 PM
To: intersystems-community/vscode-objectscript ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [intersystems-community/vscode-objectscript] Documentation Enhancement Request: ISFS (#636)

Documentation Recommendation for Server Side Editing section and Notes.ISFS subsection

  1.  Under subsection More about isfs and isfs-readonly workspace folders, give the full json for the workspace definition
This
{ "folders": [ { "name": "hsttv-demo:HSLIB", "uri": "isfs://hsttv-demo:hslib/" } ] } as opposed to this { "name": "hsttv-demo:HSLIB", "uri": "isfs://hsttv-demo:hslib/" }
a. Explicitly give the json example the header titled "example.workspace"

example.workspace
{ "folders": [ { "name": "hsttv-demo:HSLIB", "uri": "isfs://hsttv-demo:hslib/" } ], "settings": {} }

  1.  I would also personally put this example right in the section Server-side Editing, rather than under Notes.
  2.  Would also be good to emphasize that the configuration needs to happen in your vscode workspace definition, not your user definition.
  3.  Under the section Server-side Editing include a screenshot of clicking the pencil icon, like this
[vscode-docu]<https://user-images.githubusercontent.com/43207799/117184957-514bd500-ada7-11eb-952c-e7e722bed323.png>
, or have a screencast as done in the Installation section.

Thanks

**Comment by gjsjohnmurray** [comment]
@jstetson10 it's in the README at https://github.com/intersystems-community/vscode-objectscript/blob/master/README.md#more-about-isfs-and-isfs-readonly-workspace-folders

**Comment by jstetson10** [comment]
*facepalm*

Thanks,

**Comment by jstetson10** [comment]
The product documentation covers ISFS sufficiently. The README should be edited to direct readers to the documentation. In general, the README should focus on feature overview and release notes.

**Comment by isc-bsaviano** [comment]
@isc-rsingh @gjsjohnmurray I think we should remove everything from the README besides a short installation blurb with a link to the documentation and maybe the proposed API section, regardless of whether it gets included in the main docs. Does that sound reasonable?

**Comment by isc-rsingh** [comment]
Yes it does

**Comment by isc-bsaviano** [comment]
@isc-rsingh Ok, I'm going to put together a PR soon that will resolve the outstanding documentation issues

**Comment by gjsjohnmurray** [comment]
I agree

**Comment by isc-aray** [comment]
Is this related to server-side editing being deprecated in 2.8.0? I'm not sure I understand what the alternative is meant to be.

**Comment by isc-bsaviano** [comment]
@isc-aray Editing using `isfs` files and virtual workspace folders is NOT deprecated, it remains one of the two supported workflows. We did deprecate a specific setting that allowed editing files opened from the ObjectScript Explorer (used for client-side editing) due to the confusion with the server-side editing workflow. This documentation issue is old and unrelated to that decision.
