### ISSUE TITLE
Improve syntax checking for missing } or ; at the end of the class

### ISSUE THREAD

**Issue by isc-solon** [intersystems-community/vscode-objectscript#672]
In a class definition, if the editor detects a missing ; at the end of a property or parameter or index, or a missing } at the end of a method or class query or trigger, the **rest** of the code in the definition is highlighted in red and it's easy to see where the missing character is. But if the missing character is at the end of the class (the **last** class member), only the final } turns red, and it's not as easy to spot the error. Could the editor also highlight the line with the missing character itself?

**Comment by isc-bsaviano** [comment]
The red coloring comes from the LS's Studio parser tokenizing the following tokens as "errors". I don't think it makes sense to consider syntactically correct code as an error because there's an error at the end of that line.

**Comment by isc-bsaviano** [comment]
You should also see an error Diagnostic that draws your attention to the end of the class in your example

**Comment by isc-solon** [comment]
I'm testing this in a few different classes and seeing different behavior than what I **originally** saw that caused me to create this issue. I will report back with more details.

**Comment by isc-bsaviano** [comment]
@isc-solon I did some more digging and I was able to identify the issue. For Parameters specifically, you're not seeing the error diagnostic at the end of the incomplete Parameter definition line (missing closing `;`) due to the special way I calculate Diagnostics for Parameter lines. I will close this issue and open a new one in the LS repo. I'll get to this when I have time.
