### ISSUE TITLE
Export not Refreshing Open File: By design?

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#700]
I've been switching between Studio and VS Code on my current project, and noticed that a save/compile in Studio does not get automatically "refreshed" in the VS Code editor, or some notification provided that the opened file has changed on disk when I export in VS Code. Is there a way to enable this behavior?

Thanks!

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet When editing client-side (which I assume you're doing since you mentioned exporting) your exported files will not auto update. This is by design because in this workflow, the local exported files are the "source of truth". If you edit server-side like Studio, #685 added auto-refreshing of isfs server files that aren't dirty, which mimics Studio's behavior. That PR will be in the next released version of the extension, or you can try a beta version that includes it.

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet Did that answer your question? If so, please close this issue.

**Comment by DodgeDeBoulet** [comment]
Ok, thanks. I assumed the server's files would always take precedence on export, since why would you do that unless you actually wanted to overwrite the local file?

But if this is by design, I'm OK with it and will close the issue.
