### ISSUE TITLE
CSP files not compiled when edit/save on local

### ISSUE THREAD

**Issue by yidongyi** [intersystems-community/vscode-objectscript#707]
When i direct server-side editing using isfs:// folders in a workspace，it's compiled on server.

But ,I export CSP files to local. it's not compiled on server when edit/save CSP file. 

extension version : v1.0.12

**Comment by yidongyi** [comment]
extension version : v1.0.12

**Comment by isc-bsaviano** [comment]
@yidongyi What's the path to your CSP files? From the description of PR #622:

> How to use:
> - Open a workspace that contains web app files in a csp directory that matches the path on the server.
> - Open a text file in your local copy of the web app files, edit it, and then save it. The file will be automatically synced to the server.
> - Right-click on the web app directory, select "Import Without Compilation". All text files in the directory will be synced with the server.
> 
> **NOTE:** This only works with web apps that are of the format csp/*

**Comment by yidongyi** [comment]
The Path:
           |--- cls\*.cls
           |---inc\*.inc
           |--- int\*.int
           |--- mac\*.mac
           |---oth\web\*.csp

the export setting:
"objectscript.export": {
			"folder": "HIS232_223",
			"addCategory": true, 
			"map": {}, 
			"atelier": true,  
			"generated": true, 
			"filter": "", 
			"category": "*",  
			"noStorage": false,  
			"dontExportIfNoChanges": true,  
			"maxConcurrentConnections": 0
}
Right-click on the web app directory（web folder） with no response.

**Comment by isc-bsaviano** [comment]
@yidongyi What web app directory are you clicking on? If you're trying to expand a local web app folder, it can't ever "not respond" because it's a local folder on you file system. Can you open a single CSP file in the web app that you're trying to edit and give me the path to it relative to your workspace folder?

**Comment by yidongyi** [comment]
> @yidongyi What web app directory are you clicking on? If you're trying to expand a local web app folder, it can't ever "not respond" because it's a local folder on you file system. Can you open a single CSP file in the web app that you're trying to edit and give me the path to it relative to your workspace folder?

HIS232_223\oth\imedical\web\CIS.AN.AnaConsent.ZMDZX.csp

**Comment by isc-bsaviano** [comment]
@yidongyi That CSP file isn't being synced with the server because the path to it doesn't include "csp". The logic for determining whether a CSP file is synced to the server is decoupled from the export logic because many people that work with CSP and client-side source control like GitHub have their files structured in a different way than the extension's export logic. If you're not using source control, I recommend that you use server-side editing. #622 has some more details.

**Comment by yidongyi** [comment]
NOTE: This only works with web apps that are of the format csp/*

yes,  i should export csp files into csp/* rather than oth/*

**Comment by yidongyi** [comment]
> NOTE: This only works with web apps that are of the format csp/*
> 
> yes, i should export csp files into csp/* rather than oth/*
