### ISSUE TITLE
Go to Definition client side opens server version when not in same folder

### ISSUE THREAD

**Issue by bourette** [intersystems-community/vscode-objectscript#742]
I'm using client side development.  I have multiple folders representing different packages in my application.  If I open a class in one folder and attempt a go to definition on a method, it will only work if the class exists in the same folder.  Ideally, the path would be calculated for each folder and then the check for existence done instead of just the current folder.

**Comment by daimor** [comment]
It should use export settings, to find the path to the desired class. To check it, you may look to server explorer, if target class has a correct link to file on disk.

**Comment by bourette** [comment]
Export does put the file out to the correct location.  I couldn't see where it was putting it (empty output) so I deleted the file, did an export and it re-appeared.

**Comment by bourette** [comment]
Oh, my mistake, I do see the correct location in the output, but the go to definition still doesn't work.

Here are my folders
	"folders": [
		{
			"name":"HealthConnect.FHIRSQL",
			"path": "../../Volumes/P4/projects/healthshare/appmodules/HSHC-WIP/HealthConnect.FHIRSQL/latest/"
		},
		{
			"name":"HealthConnect.Common",
			"path": "../../Volumes/P4/projects/healthshare/appmodules/HSHC-WIP/HealthConnect.Common/latest/"
		}
	],

**Comment by isc-bsaviano** [comment]
@daimor Any change made for this would have to be done in `DocumentContentProvider.getUri()`. Since the LS doesn't pass `wFolderUri` as an argument, `currentWorkspaceFolder()` on line 51 is always executed. This returns the path to the folder containing the document, not the path to the whole workspace. I'm not sure if we should check every non-virtual folder in the workspace because they may be connected to different servers.

https://github.com/intersystems-community/vscode-objectscript/blob/f92afbe12fcbab2bb32425dccefc835f15b551a1/src/providers/DocumentContentProvider.ts#L50-L53

**Comment by bourette** [comment]
I think that working client side you would expect that you would be connected to a single server and that finding the first occurrence of the matching file would be suffice no matter what server you are connected to.  Performing this way would certainly be an improvement over just loading the server version.

**Comment by isc-bsaviano** [comment]
@bourette I know for sure that at least one developer at InterSystems has multi-root client side workspace connected to multiple servers. It's possible that your suggestion would be an improvement for them too but requires some thought on our end.

@daimor @gjsjohnmurray  What do you think?
