### ISSUE TITLE
Can't delete multiple classes on Server Explorer

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/vscode-objectscript#746]
As show in the video below, when multiple classes are select only one is delete.
In this example : 
Class 10 to 15 are selected and only class 15 is deleted.

VScode : 1.61
Objectscript plugin : 1.0.14
OS : Mac

https://user-images.githubusercontent.com/47849411/136773095-34fd49c3-3f92-46be-84c3-efefd6e1b82a.mp4

**Comment by isc-bsaviano** [comment]
@daimor @gjsjohnmurray I think the issue is that our command handlers for the `vscode-objectscript.explorer.export/delete/compile` commands have signatures that accept a single argument. [Here's](https://code.visualstudio.com/api/references/vscode-api#TreeViewOptions%3CT%3E) the documentation for `TreeViewOptions.canSelectMany` which is currently enabled:

> Whether the tree supports multi-select. When the tree supports multi-select and a command is executed from the tree, the first argument to the command is the tree item that the command was executed on and the second argument is an array containing all selected tree items.

I will investigate further.
