### ISSUE TITLE
BUG: Quick open not working on classes

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems-community/vscode-objectscript#855]
Quick open (Ctrl/Cmd + T) no longer shows classes in my workspace as can be seen below:

<img width="1792" alt="Screen Shot 2022-02-08 at 3 53 53 PM" src="https://user-images.githubusercontent.com/75783557/153073929-3bf64fec-9571-4036-8aff-79d301b862bf.png">

However, other class members are visible:

<img width="1792" alt="Screen Shot 2022-02-08 at 3 54 10 PM" src="https://user-images.githubusercontent.com/75783557/153073997-49feb0cd-8574-4056-a7e5-2197c78c2301.png">

I have proposed APIs enabled as I see the following in my output channel:
intersystems-community.vscode-objectscript version 1.4.2-beta.3 activating with proposed APIs available.

**VS Code version:** 
Version: 1.64.1
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Date: 2022-02-07T17:26:08.977Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

**Comment by isc-bsaviano** [comment]
@isc-kiyer [Quick Open](https://code.visualstudio.com/docs/editor/editingevolved#_quick-file-navigation) is Cmd+P, not Cmd+T. Cmd+T is for [workspace symbols](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name), which since https://github.com/intersystems-community/vscode-objectscript/pull/772 only shows class members and not classes to avoid duplicating functionality that should be provided by Quick Open

**Comment by isc-kiyer** [comment]
Ah I missed that. Hadn't used it in a while and so was confused when it suddenly stopped working. Thanks!
