### ISSUE TITLE
Odd Indenting Behavior in 1.4.4

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems-community/vscode-objectscript#912]
While writing a method (for an SQL table export task, not that this is particularly significant) I'm seeing VS Code indent a subsequent line on \<Enter\> as though I was starting a code block.

Example:
```
	Set tMobj = ##class(%SQL.Manager.API).%New() 
   	Set ok = tMobj.CheckIdentifier(.pSchemaName) // <Enter>
	Set ok = tMobj.CheckIdentifier(.pTableName)
	Set tSchemaTable = pSchemaName_"."_pTableName
   	Set tClassname = tMobj.FindClassName(tSchemaTable) // <Enter>
```
If I move the cursor to the end of the lines indicated by the **// \<Enter\>** comments, the next line is indented by 3 spaces in addition to the expected indent. If I don't type anything on the first anomalous indent, however, it's removed when I create the 2nd anomalous indent. I determined this by moving the cursor up through the lines of code and see that it returns to the left border when it gets to the line that previously had the unexpected indent.

I've tried commenting out (//) the 2nd and last line and the behavior remains the same. 

GIF attached demonstrating behavior.
![VSCodeIndent](https://user-images.githubusercontent.com/4532366/161147810-68358992-5a21-49b3-bd45-457f539c8712.gif)

**Comment by isc-bsaviano** [comment]
@DodgeDeBoulet I don't think this behavior is caused by our extension but I noticed that when I copied your sample code into an empty method I noticed the lines did not have uniform indenting and that they mixed between spaces and tabs. Here's a screenshot of what I'm seeing, with the code highlighted so you can see the whitespace characters:

<img width="496" alt="Screen Shot 2022-03-31 at 4 59 40 PM" src="https://user-images.githubusercontent.com/44776135/161148562-c0983fca-5e2e-4e50-99fe-e7ed7b887292.png">

**Comment by DodgeDeBoulet** [comment]
@isc-bsaviano Hmm. Not sure how those spaces got in there, but when I deleted them, indenting returned to normal. Guess it's not a bug!
