### ISSUE TITLE
New files pre-pend incorrect package name

### ISSUE THREAD

**Issue by mdavidovichHst** [intersystems-community/vscode-objectscript#933]
When creating a new file client side incorrect prefixes are pre-pended to the package/class name.  For example, adding a new file under the folder cls->PKG creates the class cls.PKG.NewClass when we want it to create PKG.NewClass.  The current solution is just to delete the “cls.” prefix before compile.

**Comment by isc-bsaviano** [comment]
@mdavidovichHst This is probably due to a mismatch between your export settings and the structure of your folders. The extension uses the `objectscript.export.folder` and `objectscript.export.addCategory` settings to determine which subfolders are part of the package name and which ones are part of your workspace organization.

**Comment by mdavidovichHst** [comment]
@isc-bsaviano Thanks this was correct!  I spoke to @timleavitt about this and he thought it might be a bug.  Tim were you thinking it was a bug for a different plugin?

**Comment by isc-tleavitt** [comment]
@mdavidovichHst nope, it was just a gap in understanding - I just didn't realize that the "export" settings also applied in this way for new files.

**Comment by mdavidovichHst** [comment]
@timleavitt Awesome!  Probably the easiest fix we'll have all day!
