### ISSUE TITLE
Downloading files 

### ISSUE THREAD

**Issue by pjsulin** [intersystems-community/vscode-objectscript#940]
According to this post, https://github.com/intersystems-community/vscode-objectscript/issues/854, the Download feature on the context menu is not part of the object script vscode extension.

Can that please be verified?

I'm asking because because when I use this feature on an entire package it works fine. However, when I use with a single file it modifies the package in the file, which seems to be very odd behavior for a generic download utility and odd that it would even know how to change the name of my class from mypackage.ClassName to new.name.ClassName. It changes the package to the directory structure where the file was downloaded.

Intersystems Server Manager v2.0.9
Intersystems ObjectScript 1.8.0
VSCode v1.66.2

**Comment by isc-bsaviano** [comment]
The "Download..." menu option is provided by VS Code for any file/folder that is provided by a non-default `FileSystemProvider` (i.e. the file doesn't exist in your local file system). I'm not sure why it changes the package name but since we don't explicitly support this feature and provide multiple alternatives for exporting files to your local file system (in addition to the Cache/IRIS methods for doing so) I don't think there's any action that I need to take here. If someone wants to open a PR to add this support it would be welcomed though.

**Comment by pjsulin** [comment]
Thanks for confirming. This can be closed.

**Comment by pjsulin** [comment]
I am looking to automate this download process. Is there code in this repo where I can see how that is done through atelier API?

**Comment by isc-bsaviano** [comment]
@pjsulin If you want to export a bunch of files with one click, you can use the Export Code From Server command, which uses the objectscript.export [configuration settings](https://intersystems-community.github.io/vscode-objectscript/settings/#vscode-objectscript) to determine what to export. The implementation is found here:
https://github.com/intersystems-community/vscode-objectscript/blob/14ded9b136f4f643990977a15ed0781c8f1137a0/src/commands/export.ts#L227
