### ISSUE TITLE
Feature Request: Add IntelliSense when doing dot-syntax access on a typed variable within a macro

### ISSUE THREAD

**Issue by mfortuna-isc** [intersystems-community/vscode-objectscript#983]
For example, if I declare the type of my variable using `#dim`, I would like intellisense to work within `$$$ThrowOnError` macro:
```objectscript
ClassMethod Test() {
 #Dim x As MyClass  = ##class(MyClass).%New()
 $$$ThrowOnError(x.MyMethod()) // Intellisense does not happen after typing "$$$ThrowOnError(x.". 
 // (However, it should be noted that intellisense does happen after fully typing "$$$ThrowOnError(x.MyMethod()".)
 // I would like intellisense to happen when I type "$$$ThrowOnError(x."
}
```
As the comments say, intellisense does not happen when I have typed
`$$$ThrowOnError(x.)`. I would like intellisense to happen in this scenario. (However, intellisense does pickup again after I type `$$$ThrowOnError(x.MyMethod())`)

**Comment by isc-bsaviano** [comment]
@mfortuna-isc The Language Server provides completion so I added that label. I did a quick investigation and the issue is caused by a small bug in the ObjectScript parser. When the line is in this state: `$$$ThrowOnError(x.)`, `x` is assigned the COS_Macro token and not a variable token, so the Language Server just returns and doesn't look for a type.

**Comment by isc-bsaviano** [comment]
@mfortuna-isc Unfortunately there's nothing we can do here. A macro argument can be any sequence of characters and there's no way for us to know that `x.` is a variable reference and dot operator.
